set_property PACKAGE_PIN H16 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN N20    [get_ports led[0]]
set_property PACKAGE_PIN P20    [get_ports led[1]]
set_property PACKAGE_PIN R19    [get_ports led[2]]
set_property PACKAGE_PIN T20    [get_ports led[3]]
set_property PACKAGE_PIN T19    [get_ports led[4]]
set_property PACKAGE_PIN U13    [get_ports led[5]]
set_property PACKAGE_PIN V20    [get_ports led[6]]
set_property PACKAGE_PIN W20    [get_ports led[7]]
set_property PACKAGE_PIN W19    [get_ports led[8]]
set_property PACKAGE_PIN Y19    [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]

set_property PACKAGE_PIN W18    [get_ports RGB_led_A[0]]
set_property PACKAGE_PIN W16    [get_ports RGB_led_A[1]]
set_property PACKAGE_PIN Y18    [get_ports RGB_led_A[2]]
set_property IOSTANDARD LVCMOS33 [get_ports RGB_led_A[0]]
set_property IOSTANDARD LVCMOS33 [get_ports RGB_led_A[1]]
set_property IOSTANDARD LVCMOS33 [get_ports RGB_led_A[2]]

set_property PACKAGE_PIN Y14    [get_ports RGB_led_B[0]]
set_property PACKAGE_PIN Y16    [get_ports RGB_led_B[1]]
set_property PACKAGE_PIN Y17    [get_ports RGB_led_B[2]]
set_property IOSTANDARD LVCMOS33 [get_ports RGB_led_B[0]]
set_property IOSTANDARD LVCMOS33 [get_ports RGB_led_B[1]]
set_property IOSTANDARD LVCMOS33 [get_ports RGB_led_B[2]]

set_property PACKAGE_PIN R17    [get_ports sw[0]]
set_property PACKAGE_PIN U20    [get_ports sw[1]]
set_property PACKAGE_PIN R16    [get_ports sw[2]]
set_property PACKAGE_PIN N16    [get_ports sw[3]]
set_property PACKAGE_PIN R14    [get_ports sw[4]]
set_property PACKAGE_PIN P14    [get_ports sw[5]]
set_property PACKAGE_PIN L15    [get_ports sw[6]]
set_property PACKAGE_PIN M15    [get_ports sw[7]]
set_property PACKAGE_PIN T10    [get_ports sw[8]]
set_property PACKAGE_PIN T12    [get_ports sw[9]]
set_property PACKAGE_PIN T11    [get_ports sw[10]]
set_property PACKAGE_PIN T14    [get_ports sw[11]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[4]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[5]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[6]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[7]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[8]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[9]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[10]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[11]]


set_property PACKAGE_PIN W14    [get_ports btn[0]]
set_property PACKAGE_PIN W13    [get_ports btn[1]]
set_property PACKAGE_PIN P15    [get_ports btn[2]]
set_property PACKAGE_PIN M14    [get_ports btn[3]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[0]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[1]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[2]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[3]]

